# ---------------------------------------------------------
# FortiGate VPN Configuration Template
# Auto-generated by Terraform
# ---------------------------------------------------------

config vpn ipsec phase1-interface
  edit "azure-p1-tun1"
    set interface "wan1"
    set remote-gw ${vpn_public_ip_1}
    set ike-version 2
    set keylife ${sa_lifetime_sec}
    set dpd on-idle
    set proposal ${ike_encryption}-${ike_integrity}
    set dhgrp ${dh_group}
    set psksecret "${shared_key}"
  next
  edit "azure-p1-tun2"
    set interface "wan1"
    set remote-gw ${vpn_public_ip_2}
    set ike-version 2
    set keylife ${sa_lifetime_sec}
    set dpd on-idle
    set proposal ${ike_encryption}-${ike_integrity}
    set dhgrp ${dh_group}
    set psksecret "${shared_key}"
  next
end

config vpn ipsec phase2-interface
  edit "azure-p2-tun1"
    set phase1name "azure-p1-tun1"
    set proposal ${ipsec_encryption}-${ipsec_integrity}
    set pfs enable
    set dhgrp ${pfs_group}
    set keylifeseconds ${sa_lifetime_sec}
    set auto-negotiate enable
  next
  edit "azure-p2-tun2"
    set phase1name "azure-p1-tun2"
    set proposal ${ipsec_encryption}-${ipsec_integrity}
    set pfs enable
    set dhgrp ${pfs_group}
    set keylifeseconds ${sa_lifetime_sec}
    set auto-negotiate enable
  next
end

config router bgp
  set as ${onprem_asn}
  set router-id 10.255.255.1

  config neighbor
    edit "${azure_bgp_ip}"
      set remote-as ${hub_asn}
      set update-source "azure-tun1"
    next
  end

  config network
    edit 1
      set prefix ${onprem_lan_prefix}
    next
  end
end
